### ISSUE TITLE
Does it work on windows?

### ISSUE THREAD

**Issue by ralphtheninja** [ralphtheninja/depgrep#3]
It would be nice to get some feedback on how/if it works on windows

**Comment by chiefbiiko** [comment]
![depgrep](https://user-images.githubusercontent.com/22937570/34514406-977c7dd6-f06d-11e7-89a3-1be59b917c27.PNG)

installation works fine but i am not getting any output

**Comment by ralphtheninja** [comment]
That's to be expected in this case, since no _dependents_ of depgrep (I doubt there even are any) contains the string level. Maybe search for something else :)

**Comment by chiefbiiko** [comment]
@) 
it is working just fine
thanks for this great module

**Comment by ralphtheninja** [comment]
@chiefbiiko Nice! Happy you like it :)

**Comment by ralphtheninja** [comment]
Also, thanks for helping out with testing!
